name: 部署並上傳 RSS

on:
  schedule:
    - cron: '*/5 * * * *'  # 每隔 5 分鐘運行一次

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 檢出代碼
      uses: actions/checkout@v4

    - name: 設置 Python 環境
      uses: actions/setup-python@v5
      with:
        python-version: latest

    - name: 安裝依賴
      run: |
        python -m pip install --upgrade pip
        pip install niquests feedgen

    - name: 執行 Python 腳本
      run: |
        if python rss.py; then
          echo "Python 腳本執行成功。"
        else
          echo "錯誤：Python 腳本執行失敗。"
          exit 1
        fi

    - name: 上傳 RSS 文件
      if: success()
      uses: actions/upload-artifact@latest
      with:
        name: taiwanplus-rss
        path: taiwanplus.rss
