name: RSSHub Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  #schedule:
    #- cron: '*/5 * * * *'  # 每隔 5 分鐘運行一次

jobs:
  deploy-rsshub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run RSSHub docker
        run: |
          docker run -d --name rsshub -p 1200:1200 diygod/rsshub:chromium-bundled
      - name: Fetch and download file
        run: |
          wget http://localhost:1200/pts -O ./rsshub_file.rss
      - name: 上傳 RSS 文件
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add *.rss
          git commit -m "Upload RSS file"
          git push
